# Generated by Django 5.2.12 on 2026-04-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics/"),
        ),
    ]
