# Generated by Django 5.2.12 on 2026-04-01 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0005_alter_workout_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
